### PR TITLE
Entries from ba to balzac

### PR DESCRIPTION
**Pull request by mira-gruenwald**
In this branch I copied the entries from the old list to the new one.
In some entries there is just the author but any title mentioned. I skipped those entries, as well as entries on music (e.g. Bach).
@LenaHenningsen , should I copy them anyway? And which Genre and Act Type shall we use for music, opera and art?

### CODE REVIEW

**Comment by duncdrum** [comment]
there are ways to encode non-text documents within our current data schema, see [here](http://www.loc.gov/standards/mods/mods-outline-3-6.html#typeOfResource). But within a reading database would argue that music and art require their own tables. 
P.S. @mira-gruenwald let's move the discussion to issues, which is the better place for questions and discussions.

**Comment by duncdrum** [comment]
ok i m pulling this in. We still need an answer to #59

**Comment by LenaHenningsen** [comment]
Sorry, folks, was teaching on a summer school with terrible internet access… I will answer soon, hopefully; Chia-yi is coming tonight, we will work on the database tomorrow.

Best,

Lena  

 

Von: Duncan Paterson [mailto:notifications@github.com] 
Gesendet: Donnerstag, 31. August 2017 16:33
An: LenaHenningsen/ReadingData
Cc: LenaHenningsen; Review requested
Betreff: Re: [LenaHenningsen/ReadingData] Entries from ba to balzac (#58)

 

ok i m pulling this in. We still need an answer to #59 <https://github.com/LenaHenningsen/ReadingData/issues/59>

**Comment by LenaHenningsen** [comment]
So: answer to question 1:
as to the entries with just an author. I think most of them are from Jingxuan - skip them for now, maybe mark them "check later" because for these, we have to look at the source again, maybe Chia-yi can do that later.

**Pull request merged**
