### PR TITLE
Completing entries on Djilas

### PR DESCRIPTION
**Pull request by mira-gruenwald**
@LenaHenningsen please have a look at the ActType file, I created a new act type, AT06, "to find". Do you agree, or should it simply be AT01, "to read", to prevent too many act types?

I still have to find biographical data for Xu Chenggang and Li Daxing, I hope to complete those entries later or tomorrow.

### CODE REVIEW

**Comment by LenaHenningsen** [comment]
Liebe Frau Grünwald,

prima! Ich wäre in dem Fall (Han Shaogong) für read AT01, da das ja vermutlich die zentrale Info ist; bitte kopieren Sie das Prosa-Feld in die act-tabelle hinein, dann können wir da immer nochmal nachsehen. Zu überlegen wäre eher zu differenzieren zwischen read und read clandenstinely, wobei bei vielen hierzu keine Angaben sind.

AT06 würde ich dann aus der Act Type Tabelle löschen, da ich inzwischen irgendeinen anderen AT06 definiert habe.

Herzlich,

LH

 

Von: Mira Grünwald [mailto:notifications@github.com] 
Gesendet: Dienstag, 1. August 2017 13:05
An: LenaHenningsen/ReadingData
Cc: LenaHenningsen; Mention
Betreff: [LenaHenningsen/ReadingData] Completing entries on Djilas (#48)

 

@LenaHenningsen <https://github.com/lenahenningsen>  please have a look at the ActType file, I created a new act type, AT06, "to find". Do you agree, or should it simply be AT01, "to read", to prevent too many act types?

I still have to find biographical data for Xu Chenggang and Li Daxing, I hope to complete those entries later or tomorrow.

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/LenaHenningsen/ReadingData/pull/48


Commit Summary


*	added readers and sources
*	Person-numbers


File Changes


*	M data/Act.csv <https://github.com/LenaHenningsen/ReadingData/pull/48/files#diff-0>  (5) 
*	M data/ActType.csv <https://github.com/LenaHenningsen/ReadingData/pull/48/files#diff-1>  (1) 
*	M data/Person.csv <https://github.com/LenaHenningsen/ReadingData/pull/48/files#diff-2>  (4) 
*	M data/Text.csv <https://github.com/LenaHenningsen/ReadingData/pull/48/files#diff-3>  (4) 


Patch Links:


*	https://github.com/LenaHenningsen/ReadingData/pull/48.patch
*	https://github.com/LenaHenningsen/ReadingData/pull/48.diff

**Comment by LenaHenningsen** [comment]
Can you resolve the conflicts that have arisen between master and your branch?
Best,
LH

**Comment by mira-gruenwald** [comment]
I tried to update the branch from master, but I still get an error message which tells me to resolve the conflicts first. I made some commits to the branch, deleted the Act Type etc. How should I proceed now? Can I push the commits to origin?

**Comment by duncdrum** [comment]
yes if you have stacked changes push them, then click on ``use the web editor`` below the confict warning here on github to resolve the conflicts
screenshot 2017-08-01 20 17 08

**Comment by LenaHenningsen** [comment]
It seems that all conflicts are solved. Will merge now

**Comment by LenaHenningsen** [comment]
Seems like it worked fine! Djilas is now merged and the branch is deleted.

**Comment by duncdrum** [comment]
ehm check the act and person tables

**Pull request merged**
