### PR TITLE
Fixing date format peson file

### PR DESCRIPTION
**Pull request by HUANG0421**
see #205 
> Pull-requests should be ready to merge, and quick to review. Please help your reviewer by using this form. If you require a specific reviewer you can select them on the right. 

### Please indicate relevant issues
See # .
Close # .

### Checklist
-   [ ] The title line explains what these changes do
-   [ ] All my changes are marked in the `last_modfied` column
-   [ ] All formatting changes are intentional (dates, coordinates)
-   [ ] My changes do not add empty rows
-   [ ] I checked the modified table on GitHub (click `view`)

### CODE REVIEW

**Comment by duncdrum** [comment]
@HUANG0421 please resolve conflicts, and use the template.

**Comment by HUANG0421** [comment]
About the new conflicts at Place: I just put 0 after the decimal point. :-)
What do you mean at "use the template"? Do you mean the checklist?

**Comment by HUANG0421** [comment]
And actually I don't know very well how to resolve the conflicts besides change all the differences from master branch. Is there any faster method to do it?
I've done fetch, but it still shows me the old version from me. I mean, it does not show so clearly what differences there are. Thanks for helping! :-)
(p.s. I'm now in Beijing, It may be because of the poor network connection)

**Comment by duncdrum** [comment]
HI Wenxin hope you are enjoying Beijing, especially the food. [This section](https://help.github.com/articles/resolving-a-merge-conflict-on-github/) explains how to solve conflicts. Let me know if you have connection issues, there is a workaround for that too. 
And yes by template I mean the checklist.

**Comment by HUANG0421** [comment]
I resolved the conflicts at place, but not finished yet :-) i will work on it at Saturday.

**Pull request closed without merging**
