### PR TITLE
"no" is not a date

### PR DESCRIPTION
**Pull request by duncdrum**
NULL makes more sense

### CODE REVIEW

**Comment by LenaHenningsen** [comment]
OK, i.e. we write NULL not  the number zero (0).

**Comment by duncdrum** [comment]
any reason why you didn't pull it in?

**Comment by inamoto4** [comment]
Wir wollten folgenden Unterschied machen:
"yes" for the rusticated youth
"no" for those who have lived during that time but were not affected by the rustication
"0" to those for whom it did not apply, as they were living during that time but not in China or living in a different time.

**Comment by LenaHenningsen** [comment]
Nope – well, yes, stupidity and a crying baby ;)

 

Von: Duncan Paterson [mailto:notifications@github.com] 
Gesendet: Dienstag, 18. Juli 2017 14:58
An: LenaHenningsen/ReadingData
Cc: LenaHenningsen; State change
Betreff: Re: [LenaHenningsen/ReadingData] "no" is not a date (#24)

 

any reason why you didn't pull it in?

**Comment by duncdrum** [comment]
>"yes" for the rusticated youth
>"no" for those who have lived during that time but were not affected by the rustication
>"0" to those for whom it did not apply, as they were living during that time but not in China or living in a different time.

This is fuza since we are recording year numbers here. The live-time of a person is implicit information recorded elsewhere. With ``YYYY`` in the first case and ``NULL`` in the second and third, we have a single datatype per cell, that captures the relevant info. 

Alternatively, we need another column

**Comment by LenaHenningsen** [comment]
Then I would opt for a second column;  reality is not binary, the model wants it to be, it seems.

**Comment by duncdrum** [comment]
I would suggest a numeric code nonetheless: 
*   ``01`` for yes 
*   ``02`` for no (alive but not affected)
*   ``03`` for no (alive but did not apply)
*   ``04`` for …

The year numbers for the rustication period which are currently supposed to go into this field then need their own column:
*   ``unknown`` for cases where it happened but we don't know
*   ``NULL`` for not affected/ doesn't apply/ ...

**Pull request merged**
