### PR TITLE
added some source id

### PR DESCRIPTION
**Pull request by mira-gruenwald**
see #93

### CODE REVIEW

**Comment by duncdrum** [comment]
@LenaHenningsen since the old contents of source encodes acts, we can either convert them all to foreign keys in the person table and then add acts in the act table in a separate step. Or do it in one go, when editing the person table. This would probably be easier, for data consistency. 

If you prefer the latter, I would ask @mira-gruenwald to add the acts for the converted entries to this PR, otherwise go ahead an merge.

**Comment by mira-gruenwald** [comment]
@LenaHenningsen @duncdrum @inamoto4  
Hello, what exactly do you mean by adding the acts to this PR? Should I add the act-id to the person-file? And to which column?
Best regards

**Comment by duncdrum** [comment]
@mira-gruenwald the corresponding issue is #93. `Source` is somewhat a misnomer, the data it contains is actually the individual reading acts. So these need to be added to the `act` table

**Comment by inamoto4** [comment]
@mira-gruenwald @duncdrum @LenaHenningsen 
What's the current status over here? I guess we take the person table and the act table as two different things, as we are not only transforming our old data into the new form, but might come across different acts by already existing persons, right? I can't really see why we should not merge here. 

And I guess that we settled on having altogether four columns for the sources in the person table to allow for two sources, right?

**Comment by duncdrum** [comment]
@inamoto4 the question is what the source column in person table is recording. If reading acts are recorded in the act table (where there is a source id) then this information should not be duplicated in the person table. 
The current definition in the Data Dictionary needs to be updated to reflect this. 4 acts = 4 columns (with sources) in the act table, so i m nor sure what 4 columns for sources are needed her, and how the contents of the source column in person.csv are defined.

**Comment by inamoto4** [comment]
@duncdrum 
Usually the people we are interested in are not covered by entries in peoples' dictionaries or other reference books. That means that information regarding their rustication time or living dates cannot easily be retrieved. We would often need more than one source for that. Therefore I spoke of four columns, as we would have two source_id plus two page number columns.

This is not related to single acts, which are usually described in a single source.

**Pull request merged**
