### PR TITLE
added a column to act-file

### PR DESCRIPTION
**Pull request by mira-gruenwald**
See #174
I added 'status_of_source'-column to the act-file

As proposed in the issue I added abstract values referring to the GenreType ('01' for academic writing, '02' for life-writing and '03' for fictional texts) as definition to the data dict. 
I hope this corresponds to what you had in mind :)

> Pull-requests should be ready to merge, and quick to review. Please help your reviewer by using this form. If you require a specific reviewer you can select them on the right. 

### Please indicate relevant issues
See # .
Close # .

### Checklist
-   [x] The title line explains what these changes do
-   [x] All my changes are marked in the `last_modfied` column
-   [x] All formatting changes are intentional (dates, coordinates)
-   [x] My changes do not add empty rows
-   [x] I checked the modified table on GitHub (click `view`)

### CODE REVIEW

**Comment by inamoto4** [comment]
This one might close #174 , right?

**Comment by LenaHenningsen** [comment]
yes

 

Von: inamoto4 <notifications@github.com>
Antworten an: LenaHenningsen/ReadingData <reply@reply.github.com>
Datum: Mittwoch, 31. Januar 2018 um 18:07
An: LenaHenningsen/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Review requested <review_requested@noreply.github.com>
Betreff: Re: [LenaHenningsen/ReadingData] added a column to act-file (#191)

 

This one might close #174 , right?

**Comment by LenaHenningsen** [comment]
Thanks, that seems great to me. Or would you disagree, @duncdrum

**Comment by duncdrum** [comment]
Ok I think we should merge this as is, we will need to rework 'Genre' and make some minor adjustments then. But I d much rather do that once #165 is actually complete.

**Pull request merged**
