### PR TITLE
Social Relations classifiers

### PR DESCRIPTION
**Pull request by inamoto4**
I thought about different ways to distinguish interpersonal relations. In the end I got back to the already proposed model of kinship plus another dimension with two possible qualities. This other dimension is friendship in a broad sense.
In the end this category should encompass all relations except for kinship relations. We have city friends and zhiqing comrades, but not seldom they might have been the same guys or became city friends after they returned home. In our texts we once in a while might also encounter friends in the army or party, but this in the end is about the same. The decisive quality at that time was trust, so we could also use the term confidant. /This would also mean that almost all members of clandestine literary circles belong to the first group, as everybody had to trust everybody in the fullest way.)
Another possible way to distinguish this non-kinship relation would be bosom buddy and friend. Maybe S_3 and S_4 could be possible ways to classify all relations, as proposed in the data_dict.

see #153

### CODE REVIEW

**Comment by duncdrum** [comment]
waiting on feedback on #170, I ll push final edits and corrections to this branch afterwards.

**Comment by duncdrum** [comment]
Changes are in #184 awaiting review.

**Comment by duncdrum** [comment]
@inamoto4 please don't push new and unrelated commits into an open pull-request. Use separate branches and a new PR when ready. Your changes are in the membership branch, please open a new PR when you are done working on institutions and are ready for a review.

**Comment by inamoto4** [comment]
@duncdrum 
It seems that I understood your first comment in the wrong way. My commits were related to #170 and to Social Relations.

**Pull request merged**
